### ISSUE TITLE
Bad name documentation

### ISSUE THREAD

**Issue by galactic-dust** [kerukuro/digestpp#15]
This library is not header-only, we have to include a bunch of file to get it work, and it's a big mess.

**Comment by kerukuro** [comment]
Here is the definition of header-only library from Wikipedia:

In the context of the [C](https://en.wikipedia.org/wiki/C_(programming_language)) or [C++](https://en.wikipedia.org/wiki/C%2B%2B) programming languages, a [library](https://en.wikipedia.org/wiki/Library_(computing)) is called header-only if the full definitions of all [macros](https://en.wikipedia.org/wiki/Macro_(computer_science)), [functions](https://en.wikipedia.org/wiki/Function_(computer_science)) and [classes](https://en.wikipedia.org/wiki/Class_(computer_science)) comprising the library are visible to the [compiler](https://en.wikipedia.org/wiki/Compiler) in a [header file](https://en.wikipedia.org/wiki/Header_file) form.[[1]](https://en.wikipedia.org/wiki/Header-only#cite_note-Wilson-HeaderOnly-1) Header-only libraries do not need to be separately [compiled](https://en.wikipedia.org/wiki/Compiler), packaged and installed in order to be used. All that is required is to point the compiler at the location of the headers, and then [#include](https://en.wikipedia.org/wiki/C_preprocessor) the header files into the application source.

digestpp fully conforms to this definition; it does not need to be separately compiled, packaged and installed. All that is required in order to use it is add the location of the digestpp library to the include search path of the compiler, and "#include <digestpp.hpp>" from your code, like is done in the examples (see "example.cc").

Note that "header-only library" does not imply that it consists of a single file which can be directly embedded into your own project. That would be "single-file library", not "header-only library". We never promised that. Therefore, the documentation is correct.
